### ISSUE TITLE
`opctl apply` should check pod statuses before printing that application is ready

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#105]
We need to check that every pod in `onepanel` namespace is running. Generally if all pods in `onepanel` are running we should be ok, however we need to research whether we need to check every pod in `istio-system` and `cert-manager` as well as select pods in `kube-system`.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani What about optional components? Such as `kube-logging`?

I can check this namespace, but how should the code decide it's okay if there are no resources there?
Source from params.yaml?

**Comment by rushtehrani** [comment]
We just need a blanket statement for those that says "Note: be sure to check that your pods are all running by running this command: `kubectl get pods --all-namespaces`.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani I have feature/core.105 with this functionality.
- There is a "status" command that you can run. This will check your deployment.
Let me know what you think.

I'm working on making it a part of "apply" command.
- I have code in place, just testing it in practice.

**Comment by rushtehrani** [comment]
@aleksandrmelnikov can you open a draft PR?
