### ISSUE TITLE
Move `defaultNamespace` under `application`

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#114]
In its current location, it is almost always missed.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Do I need to change 
`common/onepanel/base/configmap-onepanel-onepanel.yaml`?
The
```
data:
  # This key right here?
  applicationDefaultNamespace: $(applicationDefaultNamespace)
```

**Comment by rushtehrani** [comment]
> @rushtehrani Do I need to change
> `common/onepanel/base/configmap-onepanel-onepanel.yaml`?
> The
> 
> ```
> data:
>   # This key right here?
>   applicationDefaultNamespace: $(applicationDefaultNamespace)
>   # from defaultNamespace: $(defaultNamespace)
> ```

Might as well get it done, you'd have to update that key in onepanelio/core too I believe.

**Comment by aleksandrmelnikov** [comment]
I'll dig around

**Comment by aleksandrmelnikov** [comment]
I can't find it as well.
We do pull that configMap, `onepanel`, for database connection.. But not the default namespace as far as I can tell.
I'll remove it for now.
