### ISSUE TITLE
Clone WorkflowTemplate

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#127]
Need to be able to clone a WorkflowTemplate from UI and API.

**Comment by aleksandrmelnikov** [comment]
Clone details:
- They have to pick a unique new name for the WorkflowTemplate
- Do we copy over the history of versions?
- What about the related WorkflowExecutions? If a WorkflowTemplate had a bunch of Workflows executed, do we want to bring those over as well?
- Other details?

**Comment by rushtehrani** [comment]
> * They have to pick a unique new name for the WorkflowTemplate
Correct

> * Do we copy over the history of versions?
No, only latest template cloned in this phase.

> * What about the related WorkflowExecutions? If a WorkflowTemplate had a bunch of Workflows executed, do we want to bring those over as well?
No, this is a pure template clone in this phase.
