### ISSUE TITLE
Add `ONEPANEL_HOST=<host>` system environment variable

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#149]
Changes needed:

- Add `onepanel` ConfigMap in `onepanel` namespace.
- Add method to API to grab this value.
- Auto inject this as a parameter in Workflows.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani For bullet 2, what do you mean by API? An endpoint?

**Comment by rushtehrani** [comment]
> @rushtehrani For bullet 2, what do you mean by API? An endpoint?

Meant we need to update [this method](https://github.com/onepanelio/core/blob/master/pkg/client.go) to return this info as well.

**Comment by aleksandrmelnikov** [comment]
This should be ready for review.
