### ISSUE TITLE
Add Argo CronWorkflow

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#16]
https://github.com/argoproj/argo/pull/1758

**Comment by aleksandrmelnikov** [comment]
Added Get, List, Delete, and Update endpoints.
Some remaining questions:

Does a "Watch" endpoint make sense?

Get Endpoint
- Right now, only the CronWorkflow details are returned.
The specified WorkflowTemplate is not. If this needs to be returned, I need to add a way to track this information. I assume I would use the database?

Delete
- Deletes the CronWorkflow

Update
- Can update an existing CronWorkflow

Labels piece:
- I have code in place to set the WorkflowExecution portion, of the CronWorkflow, labels.
Is this accurate?

Lastly
- I need to clean up the Message of CronWorkflow. I think I just need the WorkflowTemplate in the Message body, and not a nested WorkflowExecution->WorkflowTemplate.
- I need to remove some remaining code from prototype attempts

**Comment by rushtehrani** [comment]
> Does a "Watch" endpoint make sense?

I don't think we need Watch since that's only relevant for a WorkflowExecution, but I defer to @Vafilor

**Comment by Vafilor** [comment]
@rushtehrani @aleksandrmelnikov At the moment I don't think we need a watch either.

**Comment by aleksandrmelnikov** [comment]
Refactored CronWorkflow message in proto.
The "CreatCronWorkflow" endpoint has had it's POST body simplified.
Example:
```
{
  "namespace": "aleksandr",
  "cronWorkflow": {
    "schedule": "*/5 * * * *",
    "timezone": "America/Los_Angeles",
    "suspend": false,
    "concurrencyPolicy": "Allow",
    "startingDeadlineSeconds": 20,
    "successfulJobsHistoryLimit": 10,
    "failedJobsHistoryLimit": 10,
    "parameters": [
      {
        "name": "Hello",
        "value": "Hello"
      }
    ],
    "workflowTemplate": {
      "uid": "2a765fa0-4c17-43ff-9ea8-3c75b1719022",
      "version": 1585264329
    }
  }
}
```

**Comment by rushtehrani** [comment]
I think the original request object made more sense because it allowed us to reuse Workflow spec directly and mapped to Argo’s structure. For example, if we add additional fields to the Workflow struct, we’d have to update the fields for CronWorkflow separately?

**Comment by aleksandrmelnikov** [comment]
I can see your point. I thought it was more complicated than we needed for CronWorkflows.
As in, we store the Workflow details inside WorkflowTemplates.
- So why pass both when we can get the information from just WorkflowTemplates.

I see that keeping WorkflowExecution maps better to Argo's structure.
But why would adding fields to Workflow struct matter to CronWorkflow?

**Comment by aleksandrmelnikov** [comment]
Reverted refactor.
POST Example:
```
{
  "namespace": "aleksandr",
  "cronWorkflow": {
    "schedule": "*/9 * * * *",
    "timezone": "America/Los_Angeles",
    "suspend": false,
    "concurrencyPolicy": "Allow",
    "startingDeadlineSeconds": 20,
    "successfulJobsHistoryLimit": 10,
    "failedJobsHistoryLimit": 10,
    "workflowExecution": {
      "parameters": [
        {
          "name": "Hello",
          "value": "Hello"
        }
      ],
      "workflowTemplate": {
        "uid": "2a765fa0-4c17-43ff-9ea8-3c75b1719022",
        "version": 1585264329
      }
    }
  }
}
```

**Comment by aleksandrmelnikov** [comment]
Manifests had to be updated; I added some permissions for crons.
feature/core.16[...] has the changes.
