### ISSUE TITLE
Add `url` and update `host` in `params.yaml`

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#160]
- `url`: for application url, Example: app.demo.onepanel.ai
- `host`: for actual domain that is used throughout the app. Example: demo.onepanel.ai

Few places that this needs to be updated and added:
- Need to [update this](https://github.com/onepanelio/manifests/blob/73db6026539756e8ad936df0c109b5e09071328a/common/onepanel/base/configmap-onepanel-onepanel.yaml#L7) and also add `ONEPANEL_URL`.
- Update [this](https://github.com/onepanelio/manifests/blob/bc56495fd7faaec3dcbe0ab9f6bca9c6c7a6e12b/common/onepanel/overlays/cloud/service-onepanelcore-onepanel.yaml#L26) and [this](https://github.com/onepanelio/manifests/blob/bc56495fd7faaec3dcbe0ab9f6bca9c6c7a6e12b/common/onepanel/overlays/cloud/service-onepanelcoreui-onepanel.yaml#L23) to `$(applicationURL)`
- I believe [these variables](https://github.com/onepanelio/manifests/blob/67e78b5b006731db77def72c987ad5a0994db1bc/common/onepanel/base/deployment-onepanelcoreui-onepanel.yaml#L25-L26) may also be affected.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani This is ready for testing.
