### ISSUE TITLE
Workflow: Status does not get updated sometimes

### ISSUE THREAD

**Issue by san999p** [onepanelio/core#166]
Sometimes when there is an error and the execution has been terminated, the status still shows Running. It gets updated only after refreshing the page.

![status](https://user-images.githubusercontent.com/57917118/80267419-6b1bed80-8666-11ea-8005-f27cabc966ce.PNG)

**Comment by Vafilor** [comment]
A update has been released that fixed issues with status not updating, need to see if this is still happening.

**Comment by rushtehrani** [comment]
Verified this by running a long training process
