### ISSUE TITLE
Expose IsAuthorized as a service

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#208]
We need to expose [IsAuthorized](https://github.com/onepanelio/core/blob/master/server/auth/auth.go#L64) as a service so that it can be used by UI to check access and toggle display of actions on Workspaces, Workspace Templates, Workflows, Workflow Templates, CronWorkflows

**Comment by aleksandrmelnikov** [comment]
I tested this endpoint with `auth token` from cli, and then the default-token in my namespace, alex.
- auth token worked
- alex token did not

But the logic should be checked.
