### ISSUE TITLE
Display input/output artifacts under parameters in node info

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#230]
Input/output artifacts should also be showing here:

![image](https://user-images.githubusercontent.com/1211823/82527269-df717180-9aea-11ea-932c-7a86534bf1dd.png)

**Comment by rushtehrani** [comment]
@Vafilor can we hide headings and subheadings if there is no data?

![image](https://user-images.githubusercontent.com/1211823/82708084-48173600-9c32-11ea-83ec-66da6bc5f19c.png)

**Comment by Vafilor** [comment]
Sure thing.
