### ISSUE TITLE
Workflow Execution Error

### ISSUE THREAD

**Issue by san999p** [onepanelio/core#240]
I am trying to execute a workflow template from the CVAT and it works for Mask-RCNN but it throws the following error for Tensorflow Object Detection.

The code is here: https://github.com/rushtehrani/cvat/blob/feat/ui-features/cvat/apps/engine/views.py#L720

The only difference between MaskRCNN and Tensorflow Object Detection is one parameter that passes string value "frcnn-res50-coco". Btw, this was used to work before I upgraded SDK.

ERROR:cvat.server:Exception when calling WorkflowServiceApi->create_workflow_execution: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'trailer': 'Grpc-Trailer-Content-Type', 'date': 'Fri, 22 May 2020 21:46:54 GMT', 'x-envoy-upstream-service-time': '601', 'server': 'istio-envoy', 'transfer-encoding': 'chunked'})
HTTP response body: {"error":"Length of string exceeds 30.","code":2,"message":"Length of string exceeds 30."}

**Comment by aleksandrmelnikov** [comment]
@san999p Thanks for reporting this

**Comment by rushtehrani** [comment]
This is due to the `workflow_execution.uid` exceeding 30 characters. I believe we can extend the limit there to 63 characters.
