### ISSUE TITLE
Template builder issues:

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#251]
[x] Cancel workspace creation from template builder takes user to workspace list
[ ] Create workspace template doesn't indicate that a workspace template was created and takes user to blank template

**Comment by Vafilor** [comment]
@rushtehrani for the second item, what should happen?

I can add a message at the top that the workspace template was created.
Should the UI stay with that current template open/editable?

**Comment by rushtehrani** [comment]
> I can add a message at the top that the workspace template was created.

Perfect, this should be similar to edit.

> Should the UI stay with that current template open/editable?

Yes
