### ISSUE TITLE
Workflow counts and status showing data from archived workflow

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#254]
![image](https://user-images.githubusercontent.com/1211823/82770162-5741e380-9dec-11ea-936e-b0af8f6ee71d.png)

It looks likes this is pulling data from the first available workflow with the same `uid`, even if it's archived

**Comment by aleksandrmelnikov** [comment]
Good catch, I think I know where this is coming from.

**Comment by aleksandrmelnikov** [comment]
I haven't been able to recreate this on minikube with the latest code changes (using dev branches).
I'm going to test on AKS and EKS with master branches, and see if the issue is present there.

**Comment by aleksandrmelnikov** [comment]
Per testing with Rush, the issue seems to have gone away on demo cluster, with 0.8.0 images.

**Comment by aleksandrmelnikov** [comment]
https://app.demo.onepanel.site/rush/workflow-templates/test-dag

**Comment by aleksandrmelnikov** [comment]
Was able to recreate this on AWS EKS cluster.
Investigating.
