### ISSUE TITLE
Add workflow template migrations for PyTorch and TensorFlow from template repository

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#288]

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Just to confirm, I don't see these templates inside the repo?

**Comment by rushtehrani** [comment]
@aleksandrmelnikov they're here: https://github.com/onepanelio/templates/tree/master/workflows

**Comment by aleksandrmelnikov** [comment]
Gotcha, thanks.
I mis-read "Workflow" as "Workspace".
