### ISSUE TITLE
Workspace Template Builder page - add support for query parameter

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#299]
So you can land on a page and select a template.

**Comment by Vafilor** [comment]
@rushtehrani Would this template be the only one displayed in that case?

If so, do we provide any visual indicator of the filter and a way to clear it?

**Comment by rushtehrani** [comment]
> Would this template be the only one displayed in that case?

This would behave the same as if I were to click on the template in template builder - it'll highlight that template and populate the editor.

**Comment by Vafilor** [comment]
@rushtehrani Okay. What happens if we have several pages of templates? 

Say I want to display template `cvat-processor`, should it sort by uid with `cvat-proceessor` first and then anything that comes after?

**Comment by rushtehrani** [comment]
@Vafilor It should be the same as if I as a user were to go to that page and select the template.
