### ISSUE TITLE
Include Istio in local deployment

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#316]
Make local deployment to Minikube and MicroK8s similar to cloud deployments and include Istio

**Comment by Vafilor** [comment]
@rushtehrani I thought we didn't do this because it took 16Gigs of RAM? Though I think I recall reading it might only be 8 gigs.

https://istio.io/docs/setup/platform-setup/minikube/

**Comment by aleksandrmelnikov** [comment]
I have the RAM to test this out (64 GB)

**Comment by rushtehrani** [comment]
I believe 8GB would work, we'll have to test to confirm. Istio is a core part of the platform so we cannot exclude it.

**Comment by Vafilor** [comment]
As a bonus, let's see if we can do a RAM check and warn the user if it might not work.

**Comment by rushtehrani** [comment]
Few notes on this:
- 8 GB RAM seems to be sufficient to ensure at least all the pods are running - this needs to be further verified with more testing 
- We need to install [MetalLB](https://metallb.universe.tf/installation/#installation-by-manifest) for any “local” deployment.
- We need to add `provider` field to application` in `params.yaml`, this way we can still distinguish between cloud and local deployments that would need MetalLB. Note that `provider` values would be `minikube`, `microk8s`, `aks` and so on.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani CLI and Manifests are testable for minikube.
- It has the metallb flag
- Deployment should have it working, to get an ip address

**Comment by aleksandrmelnikov** [comment]
Working on testing microk8s

**Comment by rushtehrani** [comment]
> Should metallb flag be required when a local provider like minikube or microk8s is used?

@aleksandrmelnikov we should actually decouple these flags and just document that MetalLB is needed if it’s not already installed.

**Comment by Vafilor** [comment]
@rushtehrani @aleksandrmelnikov 

**Feedback for Minikube**
* docs - need to update the init command to indicate that it requires metallb or update CLI to not require it. Right now CLI will tell you to add it.
* inline yaml docs - doesn’t look like IP address is working right now, so need to set a domain/fqdn. Need to remove the mention of ip address.
* metallb address: use a range that starts at minikube ip + 1, I tried the /32 format and it didn't work.
* Since we don’t have https right now, the final message isn’t accurate - it’ll never be ready without cert-manager, so it stops and tells you to check later - but the check will never succeed.
* We say `In your DNS, add an A record for` not sure if we should say this for a local deployment, maybe say add to `/etc/hosts` ?

**Comment by Vafilor** [comment]
[WIP comment]

**Feedback for Multipass**

**Documentation**
We have some inconsistencies in requirements. 
* The text says ` At least 4 Gigabytes of RAM`
* The command has `--mem 8G ` and the 
* The command comment has ` # 16G ram for Istio, recommended`

**Comment by rushtehrani** [comment]
I addressed a couple of @Vafilor concerns while I was making some minor fixes in [this commit](https://github.com/onepanelio/core-docs/pull/30/commits/71086594f5a446c2c013489c8bb97f2f79ba0065).  Deferring to @aleksandrmelnikov on the rest.

**Comment by aleksandrmelnikov** [comment]
> * inline yaml docs - doesn’t look like IP address is working right now, so need to set a domain/fqdn. Need to remove the mention of ip address.

@rushtehrani Should I make sure IP address works with local deployment?

**Comment by rushtehrani** [comment]
> @rushtehrani Should I make sure IP address works with local deployment?

@aleksandrmelnikov No, Workspaces require a domain with Istio.

**Comment by aleksandrmelnikov** [comment]
> * Since we don’t have https right now, the final message isn’t accurate - it’ll never be ready without cert-manager, so it stops and tells you to check later - but the check will never succeed.

@Vafilor I was digging into this, and I believe this might not be an issue.
I was testing with minikube and `app status` returns deployment is ready.

The code checks for the certManager in YAML, and if it's not there, it doesn't check for it.
![image](https://user-images.githubusercontent.com/10407733/84834814-1d2cc180-afe7-11ea-8a2c-cfdb314c0fa7.png)
