### ISSUE TITLE
[Needs Verification] Missing Data from newly created Workflow Template

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#318]
Note:
 This might be because I'm using an older API version. Need to test after using newer API version.

<img width="1375" alt="Screen Shot 2020-06-03 at 3 03 18 PM" src="https://user-images.githubusercontent.com/7330539/83693771-9241d500-a5ab-11ea-8812-dbd3b0b69a70.png">

Modified At and Versions are missing values.

**Comment by rushtehrani** [comment]
@aleksandrmelnikov can you verify this on your new cluster?

**Comment by aleksandrmelnikov** [comment]
Spun up a v0.10.0 cluster at https://app.web-demo.onepanel.ai/default/workflow-templates

![image](https://user-images.githubusercontent.com/10407733/83926997-58ee9e00-a740-11ea-8295-cea2914a0671.png)

![image](https://user-images.githubusercontent.com/10407733/83927012-6572f680-a740-11ea-90b9-e9c1131442c5.png)

![image](https://user-images.githubusercontent.com/10407733/83927030-76236c80-a740-11ea-8184-4bb4af4256d1.png)

Overall, looks to be working.

**Comment by rushtehrani** [comment]
Closing since this is now working
