### ISSUE TITLE
Manifests caching issue when opctl is upgraded

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#344]
Manifests for older versions seem to cache when using an upgraded `opctl`. For example, if we upgrade `opctl` from 0.9.0 to 0.10.0, 0.9.0 manifests are still used.

**Comment by IslamHeggy** [comment]
A missed params.yaml is generated too. 
It has conflicting parameters from both versions 

![image](https://user-images.githubusercontent.com/11975703/84211755-61d2cd00-aabc-11ea-9a92-5a102a8b4d58.png)

**Comment by aleksandrmelnikov** [comment]
> A missed params.yaml is generated too.
> It has conflicting parameters from both versions
> 
> ![image](https://user-images.githubusercontent.com/11975703/84211755-61d2cd00-aabc-11ea-9a92-5a102a8b4d58.png)

I have been unable to recreate this so far, can you comment how you got this to happen?
@IslamHeggy

**Comment by IslamHeggy** [comment]
@aleksandrmelnikov So Basically this resulted when I created a params,yaml after uprading the opctl from 0.9 to 0.10 in the same directory.

Steps to reproduce: 

* Install opctl v0.9 and create a new params.yaml

* Create a new deployment using this version

* Install opctl v0.10 and in the same directory remove the old params.yaml and create a new one using the new version 

* A params.yaml will be created and u will find it missed 

These are the steps I did to get the error

**Comment by aleksandrmelnikov** [comment]
Thanks, I'll try recreating.
