### ISSUE TITLE
Permission denied creating a workflow after being inactive for an hour  

### ISSUE THREAD

**Issue by IslamHeggy** [onepanelio/core#345]
So after being inactive for about an hour, It seems that the authentication token expired. 

The behavior was getting a permission denied while trying to create a new workflow and after that I went back to another page then I got redirected to the login page to enter a new token.

I think the ideal behavior can be redirecting to the login page and not showing the permission denied with a message shows authentication token expiry

**Comment by rushtehrani** [comment]
This was addressed with recent changes to EKS
