### ISSUE TITLE
Hide UI buttons based on permissions

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#373]
- Workspace template builder
- Create workspace
- Create Workflow template
- Any menu items in context menus (check on menu open)

**Comment by Vafilor** [comment]
@rushtehrani checking the permissions required here. Do these look right?

Workspace Template Builder
* *list* workflowtemplates

Create Workspace
* *create* workspaces

Create Workflow Template
* *create* workflowtemplates

Workflow Execution Context Menu

* rerun - *create* workflows
* terminate - *update* workflows

Workspace Context Menu

* resume - *update* workspaces
* terminate - *delete* workspaces
* pause - *update* workspaces

**Comment by rushtehrani** [comment]
@Vafilor yes, those look right.

**Comment by rushtehrani** [comment]
@Vafilor was this addressed?

**Comment by Vafilor** [comment]
@rushtehrani No, not all of these are in the code yet.
