### ISSUE TITLE
Workspaces - CVAT - Get available node pools via SDK

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#388]
![image](https://user-images.githubusercontent.com/1211823/86283199-68250800-bb95-11ea-8f69-acba393bfbc5.png)

The machine type selection should use the [get_config](https://github.com/onepanelio/python-sdk/blob/master/docs/ConfigServiceApi.md#get_config) call to get a list of node pools.

Also change "Select machine type" label to "Select node pool"

**Comment by savan77** [comment]
@rushtehrani `ConfigServiceAPI` isn't available on the [master](https://github.com/onepanelio/python-sdk/tree/master/core/api/api).

**Comment by Vafilor** [comment]
> @rushtehrani `ConfigServiceAPI` isn't available on the [master](https://github.com/onepanelio/python-sdk/tree/master/core/api/api). I installed latest `onepanel-sdk` and getting `AttributeError: module 'onepanel.core.api' has no attribute 'ConfigServiceApi'`.

@savan77 

Please try `pip install onepanel-sdk==0.12.0b1`

Here's a sample script to test.

```python
from __future__ import print_function

import time
import onepanel.core.api
from onepanel.core.api.rest import ApiException
from pprint import pprint

configuration = onepanel.core.api.Configuration(
    host = "http://localhost:8888" # change me
)

configuration = onepanel.core.api.Configuration(
    host = "http://localhost:8888",
    api_key = {
        'Bearer': 'token'
    }
)
configuration.api_key_prefix['Bearer'] = 'Bearer'

# Enter a context with an instance of the API client
with onepanel.core.api.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = onepanel.core.api.ConfigServiceApi(api_client)

    try:
        api_response = api_instance.get_config()

        # print(api_response.node_pool.options)

        pprint(api_response)
    except ApiException as e:
        print("Exception when calling AuthServiceApi->is_authorized: %s\n" % e)
```

Response

```json
{
  'api_url': 'https://test.andrey-3.onepanel.io/api',
  'domain': 'andrey-3.onepanel.io',
  'fqdn': 'test.andrey-3.onepanel.io',
  'node_pool': {
    'label': 'beta.kubernetes.io/instance-type',
    'options': [
      {
        'name': 'CPU: 2, RAM: 8GB',
        'value': 'Standard_D2s_v3'
      },
      {
        'name': 'CPU: 4, RAM: 16GB',
        'value': 'Standard_D4s_v3'
      },
      {
        'name': 'CPU: 8, RAM: 32GB',
        'value': 'Standard_D5s_v3'
      }
    ]
  }
}```

**Comment by savan77** [comment]
Thanks @Vafilor I tried this Friday and it seems to work. Also, that two `configuration` objects is a typo or intentional?

**Comment by Vafilor** [comment]
> Thanks @Vafilor I tried this Friday and it seems to work. Also, that two `configuration` objects is a typo or intentional?


Whoops, that's a typo. Please use the second one.
