### ISSUE TITLE
Python SDK - return metadata from create_workflow_execution

### ISSUE THREAD

**Issue by savan77** [onepanelio/core#391]
It will be really useful if the `create_workflow_execution` returned some metadata that can be used in many ways. 
Some of the metadata that I can think of now is as follows, we can add more as we move forward.
1 - URL of the executed workflow.

**Comment by Vafilor** [comment]
@savan77 I think this one has been done, can you confirm?

**Comment by savan77** [comment]
@Vafilor yes, it works.

**Comment by Vafilor** [comment]
@savan77 Cool, closing it.
