### ISSUE TITLE
Workspaces - CVAT - Show trained models in connected file storage

### ISSUE THREAD

**Issue by savan77** [onepanelio/core#397]
The shared storage is shared between Create task and Create model's connected file storage. So, we see the same files in Create model as we do while creating new tasks. This forces us to use whole bucket in file syncer and a lot of times the size of the bucket can be huge. Our current directory structure in S3 is as follows: `<prefix> -> <namespace> -> <workspace> -> datasets/models -> <trained-model>` which makes it harder to show only models.

We can either change our directory structure and store all the models in a separate folder along with the input data. Or change prefix (as an env var) to store data in the same directory as the input data. But this will still have datasets in there which we don't need in filesyncer.

**Comment by rushtehrani** [comment]
@savan77 not sure if this is relevant with the models becoming serverless APIs, can you confirm?

**Comment by savan77** [comment]
Yes, not required with serverless APIs.
