### ISSUE TITLE
Allow users to edit completed workflow's parameters before rerunning 

### ISSUE THREAD

**Issue by savan77** [onepanelio/core#404]
Sometimes users want to change one or two parameters and run again. Currently, we can rerun a workflow but can't edit it before execution. I can think of two possible solutions:
1- Show parameters and allow editing (similar to Execute workflow popup) when the user clicks on Rerun. The default parameters should be same as the ones in completed workflow. Then, users can change whatever parameters they want to change and rerun.
2 - Another way is to have two options in a menu- `Rerun` and `Edit and Rerun`. Rerun's behavior will be the same. But Edit and Rerun will be just like (1).

**Comment by rushtehrani** [comment]
I think we should go with #1 but also allow them to select another template version as well.
