### ISSUE TITLE
Can't download output artifacts when the file is large

### ISSUE THREAD

**Issue by savan77** [onepanelio/core#414]
After the workflow has been completed, if I try to download artifacts (i.e logs) of size  ~10MB or higher nothing happens. There is no error or anything else. The file also does not get downloaded.

Here is one for your reference: https://app.cnas-re-uog.onepanel.io/crb/workflows/tf-object-detection-training-44n98.

**Comment by aleksandrmelnikov** [comment]
One issue is too many requests error.
`polyfills-es2015.2987770fde9daa1d8a2e.js:1 GET https://app.cnas-re-uog.onepanel.io/api/apis/v1beta1/crb/workflow_executions/tf-object-detection-training-44n98/artifacts/artifacts%2Fcrb%2Ftf-object-detection-training-44n98%2Ftf-object-detection-training-44n98-984996726%2Fmain.log 429`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by aleksandrmelnikov** [comment]
Found this error:
```
{"error":"grpc: received message larger than max (16060619 vs. 4194304)","code":8,"message":"grpc: received message larger than max (16060619 vs. 4194304)"}
```
So it looks like that log file is too large for GRPC to return.

**Comment by Vafilor** [comment]
@aleksandrmelnikov How's this looking? Will it make it into this release?
