### ISSUE TITLE
JupyterLab workspace

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#415]
- Should be run as root 
- Should have one docker image for latest TensorFlow GPU
- Another docker image for latest PyTorch GPU
- The following extensions:
  - jupyter-widgets/jupyterlab-manager
  - [Git](https://github.com/jupyterlab/jupyterlab-git) with [GitHub](https://github.com/jupyterlab/jupyterlab-github)
  - [TensorBoard](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks), see [this notebook](https://github.com/tensorflow/tensorboard/blob/master/docs/graphs.ipynb) for validation
  - jupyter-matplotlib
  - nbdime-jupyterlab
  -  jupyterlab/debugger

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Should I store the Dockerfile in this repo? https://github.com/onepanelio/templates/tree/master/workspaces/jupyterlab

**Comment by aleksandrmelnikov** [comment]
@rushtehrani I believe Tensorboard is part of Tensorflow right?
Should Tensorboard be also available on the Pytorch image?

**Comment by rushtehrani** [comment]
> @rushtehrani I believe Tensorboard is part of Tensorflow right?
> 
> Should Tensorboard be also available on the Pytorch image?

It works with both PyTorch and TensorFlow. See https://pytorch.org/docs/stable/tensorboard.html. It is its own separate tool and can run as a sidecar container.

**Comment by aleksandrmelnikov** [comment]
Gotcha okay

**Comment by aleksandrmelnikov** [comment]
Initial PR is available.
Need to do testing for required jupyter extensions, and then the GPUs.

**Comment by rushtehrani** [comment]
@aleksandrmelnikov Looks like we need `xeus-python` [kernel](https://github.com/jupyterlab/debugger#usage) to use the debugger. Can you include that in here?

**Comment by rushtehrani** [comment]
Can we also look into installing [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp#installation)

**Comment by aleksandrmelnikov** [comment]
Absolutely, I'll try out both.

**Comment by aleksandrmelnikov** [comment]
@rushtehrani
Updated dockerfiles to support the following
- Jupyterlab 2.2 and greater
- Jupyter lsp
- Xeus Python

I also fixed up Tensorflow source build to work with Conda.
Builds in progress, will test on GPU once ready.

**Comment by rushtehrani** [comment]
@aleksandrmelnikov were you able to do anything to reduce image size?

**Comment by aleksandrmelnikov** [comment]
I haven't looked at that yet. I'll do that next.
