### ISSUE TITLE
Add TensorBoard to Workflows

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#416]
# Issue
We want to be able to run TensorBoard as a side car container for workflows, particularly
the workflow container that is doing the training.

This can be added as a sidecar container in the manifest.
It needs to make sure that it also has the same volume mounted as the training container so the data is shared
and it can read it and draw the data.

The UI should show a tensorboard button under artifacts (sidebar on the right) when this node is selected.

Eventually this should launch on demand, but that might be tough because of time and volume mount sharing.

**Comment by aleksandrmelnikov** [comment]
When running a workflow, we want Tensorboard to be available.
- This way, a user can inspect the training progress as the training is running

In our usual workflow, we have something like...

![image](https://user-images.githubusercontent.com/10407733/94743391-28082980-032c-11eb-878f-6a9ad3c9dd0f.png)


In `main_training`, the bulk of the training is running.
When that box is selected, we want to add a button, "TensorBoard", that the user can click on.

![image](https://user-images.githubusercontent.com/10407733/94743409-2f2f3780-032c-11eb-9a71-44bfad43a588.png)


TensorBoard reads logs, which are expected to stream constantly.
- So attach the same volume that the container is writing logs to

Look into sidecars that argo supports.
- https://argoproj.github.io/argo/examples/#sidecars
- We don't want to block the workflow from being marked completed, with this extra container
- Does this container end when the workflow finishes?

We want to provide the side-container in the template.
- Our system will look for "sys" prefix in the name.
- Like "sys-filesyncer"
	- If possible, use labels or annotations
	- If we can, update to use labels elsewhere

Our system will generate virtual service.
- Points to the container
- They click on the button, new tab, they see the tensorboard
- Virtual service should be the sub-domain
	- Possibly /path at the end of the url
	- Use the name of the container
		- Be wary of 63 characters limit in sub-domain

Tell user, in documentation and comments.
- Will show a UI button

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Should the preview UI display the side-car containers?

**Comment by rushtehrani** [comment]
@aleksandrmelnikov I think it should show all containers... I'm debating where the button for TensorBoard would go and will get back to you.

**Comment by aleksandrmelnikov** [comment]
Per discussion, UI Implementation piece

uuid-namespace.domain
len(uuid-namespace) <= 63

Endpoint
return sidecars, with their endpoint, and template name
input: namespace/workflow_uid
```
GET: /apis/v1beta1/{namespace}/workflow_executions/{uid}/sidecars
[
   {
      "sidecar": "tensorboard",
      "template": "pytorch",
      "endpoint: "www.wikipedia.com"
   },
   {
      "sidecar": "tensorboard-2",
      "template": "pytorch",
      "endpoint: "www.wikipedia.com"
   }
]
```
When you go to a workflow execution - it makes this request.
When selecting a node
Check template name
Check if you have sidecars (mapped template name -> sidecars)
Show the sidecars in the UI somewhere

**Comment by rushtehrani** [comment]
Shouldn't the endpoint for this be similar to files and metrics? Those are specific to the pod/task.
```
GET api/apis/v1beta1/{namespace}/workflow_executions/{worfklow-uid}/pods/{pod-uid}/sidecars
```

**Comment by Vafilor** [comment]
@rushtehrani @aleksandrmelnikov We can do that. The original intent with the general endpoint was to make less requests.

**Comment by rushtehrani** [comment]
Question: aren't the sidecars already present in the YAML? Do we actually need a separate API call or should we just parse the YAML and display that information? I believe we're doing this for arguments?

**Comment by Vafilor** [comment]
@rushtehrani Yes, they are present in YAML. But we don't know the endpoints generated for each sidecar.

**Comment by aleksandrmelnikov** [comment]
If we're focused on the yaml piece, I could try adding annotations to the pod yaml.

**Comment by rushtehrani** [comment]
@aleksandrmelnikov can you remind me how the endpoints are generated again? I know we use  `{uid}--{namespace}.{domain} but I don't recall how we come up with the `uid`.

**Comment by aleksandrmelnikov** [comment]
Sure thing.
We didn't discuss the UID piece, so I use a UUID generator library.
- So it's actually, uuid-namespace, restricted to 63 characters.

I'm open to adjusting this.

**Comment by rushtehrani** [comment]
> * So it's actually, uuid-namespace, restricted to 63 characters.

That makes sense, just to clarify, we need two `-` between `uuid` and `namespace`.
