### ISSUE TITLE
Regression: user defined workspace/workflow parameters are getting displayed after system params.

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#429]

**Comment by Vafilor** [comment]
@rushtehrani I believe this was fixed?

**Comment by rushtehrani** [comment]
Yes, fixed here: https://github.com/onepanelio/core/pull/427/commits/2eec349af9d3a6f3a5224df2660a0560dcaf5ba4

**Comment by Vafilor** [comment]
@rushtehrani Cool, closing.
