### ISSUE TITLE
Search and filter by labels

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#492]
One use case for this is adding specific labels from CVAT executed Worfklows or categorizing Workflows by experiment names.

**Comment by Vafilor** [comment]
@rushtehrani Do we have any kind of UI mockup for this? We can later expand this to include searching by name, etc.

**Comment by rushtehrani** [comment]
@Vafilor here's a quick first phase implementation of this we can discuss: https://label-filter-example.stackblitz.io
