### ISSUE TITLE
Workflow - Make custom model Workflow creation easier

### ISSUE THREAD

**Issue by savan77** [onepanelio/core#571]
A lot of users might want to add support for different models. It would be great if we can make this process easier. It was found that following are potential issues while creating a new Workflow.
- Dependencies
The pytorch/tensorflow image might not have all the required dependencies. We can use our JupyterLab image which has many libraries installed.
- Path issues
Since users need to change input and output paths based on mounts in the template, a lot of time this creates a problem because of incorrect paths or typos. I am not sure if we can do something here since it depends on user's code.

**Comment by rushtehrani** [comment]
Based on latest discussion, we need to:

- Repurpose MaskRCNN template and use the JupyterLab image.
- Add this template in the New Workflow Template form.

**Comment by savan77** [comment]
Yes, I will modify the MaskRCNN template.
