### ISSUE TITLE
Add VSCode image and template

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#609]
Ideally, this image should be built on the image layer below JupyterLab image which includes TensorFlow and PyTorch.

Note, we need to install the Python extension and upgrade to the latest `code-server` release which is currently 3.5.0.

To install an extension, you need to run the following command after installing `code-server`:

```bash
code-server --install-extension ms-python.python
```

**Comment by aleksandrmelnikov** [comment]
Additionally, we need the following to persist during pause & workspace shutdown.
- pip install
- vscode extensions
- jupyterlab extensions

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Regarding pip package persistence, one issue I see.

Say we install conda & pip to `/data`.
If we mount a volume to `/data`, it'll wipe what we install during the docker build process.

We could do something similar to our SAAS offering, where we copy the packages and put them back?
