### ISSUE TITLE
Persist pip packages, jupyterlab extensions, and vscode extensions between switching and pausing.

### ISSUE THREAD

**Issue by aleksandrmelnikov** [onepanelio/core#623]
Outline
Additionally, we need the following to persist during pause & workspace shutdown.

- pip install
- vscode extensions
Code server supports --extensions-dir
- jupyterlab extensions

We want to put the functionality into the template.
- Less work
- We can give them a best practices, default template
- We don't need to support it in the API core.

One idea was to allocate a specific volume, to store the data.
- Issue is there is a limitation on how many volumes can be run and attached. So we want to avoid contributing to that limit.

Save the packages to a volume.
- Look at attached volumes. Use the biggest one.
- Tie into postStart, preStop
- postStart: Pull the packages from a volume, into the installation directories
- preStop: Push to volume
- Warn user with a comment about running out of space. And a hint in the volume field.
- Documentation

We don't want to use S3/Object Storage because that is more coding effort to support.

Reference:
https://github.com/onepanelio/core/issues/609#issuecomment-699182224

**Comment by aleksandrmelnikov** [comment]
@rushtehrani I don't think we can implement this in the template yaml, unless I am missing something?
We have to use container lifecycle hooks right? So this has to be added in the API Core?

**Comment by rushtehrani** [comment]
@aleksandrmelnikov I might be missing something but our `WorskspaceSpec` uses K8s' container definition: https://github.com/onepanelio/core/blob/8b4a70d95898a89c3e47dfd3cef6006bd68461b0/pkg/workspace_types.go#L59

**Comment by aleksandrmelnikov** [comment]
Ah, okay, I think I jumped a few steps; let me review.
