### ISSUE TITLE
Cvat File Syncer UI - support the file syncer downloading more than once.

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#644]
Right now the file syncer UI only works with the initial download. If more files are downloaded, the UI does not update.

We need to support

1. When files are being downloaded, the UI should show a message to that effect.

2. When files are done downloaded, the UI should show a “refresh” link that will refresh the files so we can see the latest in the UI

3. If files start downloading again because there are changes, we should go back to 1.

4. If you open the page, and there are no files being downloaded (because they finished, or there were none) there should be no message.

**Comment by rushtehrani** [comment]
@Vafilor was this one addressed?

**Comment by Vafilor** [comment]
@rushtehrani Yes.
