### ISSUE TITLE
Node pool value is not showing up under parameters

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#650]
![image](https://user-images.githubusercontent.com/1211823/95686616-ceb5bb00-0bb3-11eb-921a-54592db93e58.png)

**Comment by Vafilor** [comment]
@rushtehrani Where did you see this issue? I tried it on my end, but I am seeing a nodepool.

**Comment by rushtehrani** [comment]
This was actually due to a CVAT issue that is now resolved.
