### ISSUE TITLE
CVAT node pool and GCS S3 support fixes

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#651]
- [x] Node pools are pulling the default node pool value instead of API values
- [x] GCS S3 interoperability mode is not working when pushing data to training workflow
- [x] Update CVAT template and corresponding migration

**Comment by rushtehrani** [comment]
Note that CVAT workspace template needs to also be updated to use the latest images with these fixes

**Comment by savan77** [comment]
@Vafilor can you provide me the latest tag for file syncer image so that I can send a PR for CVAT template.
