### ISSUE TITLE
Update CVAT authentication

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#652]
CVAT auth needs to be updated as follows:

- Check username and password
- If check passes and username is `admin`, then create user in CVAT as admin.
- if check passes and username is not `admin`, then create user in CVAT as regular user.
- If check doesn't pass, present user with CVAT login screen.

**Comment by aleksandrmelnikov** [comment]
Testing image `0.13.2_cvat.1.0.2b`.
- It has updated authentication logic to reduce onepanel api calls
