### ISSUE TITLE
Add labels to training workflows coming from CVAT

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#654]
Add the following labels to training workflows creates from CVAT:
- `workspace-uid: <uid>` - note that this is the `uid` not `name`
- `cvat-job-id: <cvat-job-id>` - this is the job id in CVAT

**Comment by savan77** [comment]
Following commit fixes this issue: https://github.com/onepanelio/cvat/pull/21/commits/78e471b68f8de3577b2cfdcf82996d961e26eed0
