### ISSUE TITLE
onepanel ui: going from 0 workspaces to creating a new one - the new one does not immediately show up. You have to refresh the page.

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#708]
This issue includes a couple of parts

1. When we create a workspace, the UI still believes there are no workspaces at all, so it doesn't update.

  * This can be fixed by making a request to check if there any workspaces if there are none whenever we do a poll. Note - we can't update the "any workspaces" flag in the poll because there might be filters applied. If there are no filters, it can be.

2. When we delete a workspace, the status goes to terminating and eventually terminated. So there is a time delay between clicking delete and the eventual delete. 

* This can be fixed by updating the "any workspaces" flag when we have 0 results and we have no filter. 
Alternatively, we could implement a state and keep track of things like - did that one workspace get deleted, etc. However, this is a bit more involved and error prone.

**Comment by rushtehrani** [comment]
Another similar issue to this:
- Going from 1 to 0 Workspaces, the last Workspace remains unless you refresh

**Comment by rushtehrani** [comment]
Also, when going from 1 to 0, this should show the call to action empty view vs "No workspaces found":
![image](https://user-images.githubusercontent.com/1211823/98609734-d3e55300-22a2-11eb-8283-f158c44f34ae.png)

**Comment by Vafilor** [comment]
There is code in place for this. More testing is needed to make sure performance isn't impacted.
