### ISSUE TITLE
Core-UI: Metrics - UI visuals

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#725]
Workflows should now display metrics. 

For listing workflows, this should show one or two of them (need to see how much space it takes) with a "Show more" button or equivalent that allows you to see the rest.

The idea here is to be able to see some since you are also going to be able to filter by metrics.

The Workflow View page should have a metrics section that looks like the current node info metrics section - bold key, grayish value.

**Comment by rushtehrani** [comment]
Note about metrics, they can be raw numbers or percentages, example:

```javascript
[
    {
      "name": "accuracy",  // Name of metric, should be string
      "value": 0.98,             // Value of metric, should be a `number`
      "format": ""                // Optional, valid values: "" or "%"
    },
    ...
]
```
