### ISSUE TITLE
STOP SPAMMING ME

### ISSUE THREAD

**Issue by cookiengineer** [onepanelio/core#742]
```
You are receiving this email because you opted in at CVPR. We will occasionally send customers who opted-in informational content. Sent by Onepanel Inc.
```

No, I was definitely not at CVPR.

I unsubscribed from your newsletter already 3 times.

Stop fucking spamming me. I definitely will never even remotely consider to use your software now.

Also, GDPR applies. I'm a European citizen and your marketing campaigns are illegal here. If you don't follow the law, expect that my lawyer will send you the next message.

**Comment by rushtehrani** [comment]
@cookiengineer We definitely do not mean to spam anyone. Once you are unsubscribed, we make sure you're not receiving any emails. Please DM us on [Twitter](https://twitter.com/onepanelio) if possible with the email(s) you received the emails so we can make sure you're unsubscribed?

**Comment by cookiengineer** [comment]
@rushtehrani This was not the case. As I said, I unsubscribed 3 times already, and I am now getting double times the email. I already wrote you on Twitter when you spammed me the first time, without any reply.

As I said, I never agreed for you to send me spam. This was never allowed, and I never subscribed in the first place.

**Comment by rushtehrani** [comment]
@cookiengineer which Twitter account did you DM or mention? I don't see any messages or mentions from anyone about getting spammed. We use software to make sure people are opted in and can easily unsubscribe and haven't had any issues in the past. We're trying to confirm that you are unsubscribed but need to know the email address(es) to double check.
