### ISSUE TITLE
Changing fqdn / domain in params.yaml does not automatically update existing workspace templates .

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#753]

**Comment by rushtehrani** [comment]
The issue happens because environment variables are saved on [Workspace Template creation](https://github.com/onepanelio/core/blob/master/pkg/workspace_template.go#L398-L409) as opposed to [Workspace creation](https://github.com/onepanelio/core/blob/master/pkg/workspace.go#L226).
