### ISSUE TITLE
bug: nvidia-device-plugin-daemonset deployment returns CrashLoopBackOff

### ISSUE THREAD

**Issue by inohmonton99** [onepanelio/core#789]
**Describe the bug**
Error: failed to start container "nvidia-device-plugin-ctr": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--fail-on-init-error=false": executable file not found in $PATH: unknown

MountVolume.SetUp failed for volume "default-token-rnbds" : failed to sync secret cache: timed out waiting for the condition

**`opctl` version**
```bash
$ opctl version
CLI version: v0.16.0-rc.2
Manifest version: v0.16.0-rc.2
API version: v0.16.0-rc.2
Web UI version: v0.16.0-rc.2
```

**`opctl init` command**
You can find this at the top of your `params.yaml` file. [e.g. `opctl init --provider eks --artifact-repository-provider s3 --gpu-device-plugins nvidia`]
```bash
opctl init --provider eks ^
  --artifact-repository-provider s3 ^
  --gpu-device-plugins nvidia
```

**Kubernetes information**
 - Cloud provider: EKS
 - Kubernetes version: 1.18

**Machine information**
- OS: Windows 10
- Browser: Microsoft Edge

**Screenshots**

**Comment by rushtehrani** [comment]
Looks like [nvidia-device-plugin](https://github.com/NVIDIA/k8s-device-plugin/blob/master/nvidia-device-plugin.yml) needs to be updated.
