### ISSUE TITLE
Secret not auto-generated

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#81]
I ran into this while deploying on microk8s. I got to executing a workflow and then the web failed (with no error message) because the secret was not created.

I propose testing if the secret exists on core startup and if it doesn't, create it.

Thoughts @rushtehrani @aleksandrmelnikov ?

**Comment by aleksandrmelnikov** [comment]
Which secret was missing??
Shouldn't the deployment be creating all the necessary secrets?

**Comment by Vafilor** [comment]
`onepanel-env-default` Ideally it should.

**Comment by rushtehrani** [comment]
Hmm, this worked for me before. I'm about to run another cluster, will let you know.

**Comment by rushtehrani** [comment]
Addressed in https://github.com/onepanelio/manifests/pull/32
