### ISSUE TITLE
Request for Data Augmentation Pipelines (Workflows)

### ISSUE THREAD

**Issue by animikhaich** [onepanelio/core#816]
**Is your feature request related to a problem? Please describe.**
Training workflows are great. However, it would be helpful if some basic Data Augmentation (Images) workflows added to the list of features. This would allow the training of better and more robust models.

**Describe the solution you'd like**
- For Data Augmentation, [Albumentations](https://github.com/albumentations-team/albumentations) can be used
- An example of a well-executed Data Preprocessing and Augmentation pipeline is: [Roboflow](https://roboflow.com/)

**Describe alternatives you've considered**
At this moment, the best solution is to:
- Integrate Augmentation directly into the training framework (Eg, Tensorflow Object Detection API already performs some basic color augmentations)
- Download the Annotations from CVAT, augment them using an offline script, and then train them separately. (Does not really add much value, can be done with Vanilla CVAT as well)

**Comment by rushtehrani** [comment]
The high level plan to support the first iteration of this as follows:

- Include Albumentations in the upcoming [onepandl/dl](https://hub.docker.com/repository/docker/onepanel/dl) image
- Provide Workflows that use Albumentations to augment data in one Workflow Task and then feed that data into a subsequent Workflow Task for training.
- Provide JupyterLab notebook examples of Workflows created by upcoming Python SDK that allow users to interact and view augmentations before generating and executing the Workflow.

I will follow up with an actual example of the JupyterLab notebook.

Open to feedback and suggestions for other libraries.

**Comment by rushtehrani** [comment]
We have the first version of this working by adding both [imgaug](https://github.com/aleju/imgaug) and [Albumentations](https://github.com/albumentations-team/albumentations). Here's an [example](https://github.com/onepanelio/templates/tree/master/workflows/tf-object-detection-preprocessing-training) with TFOD integration.

This will also be added to the next release as the default template for TFOD training.

**Comment by rushtehrani** [comment]
Data augmentations are now supported for both [TFOD](https://github.com/onepanelio/templates/tree/release-v0.18.0/workflows/tf-object-detection-training) and [MaskRCNN](https://github.com/onepanelio/templates/tree/release-v0.18.0/workflows/maskrcnn-training) . They can also be run as separate pipelines.  [See documentation](https://docs.onepanel.ai/docs/reference/workflows/data-augmentation) and [stand-alone template](https://github.com/onepanelio/templates/tree/release-v0.18.0/workflows/albumentations-preprocessing).
