### ISSUE TITLE
Allow Data Sharing (Mount Common Volumes) across multiple Workspaces

### ISSUE THREAD

**Issue by animikhaich** [onepanelio/core#817]
**Is your feature request related to a problem? Please describe.**
Let's assume that there are two workspaces created:
- Workspace 1: CVAT
- Workspace 2: A Custom Container containing a Jupyter Notebook designed to take Pascal VOC dataset as input and train an EfficientDet model

Expected Steps:
1. Workspace 1 contains CVAT which annotates the dataset
2. The Annotated Dataset Dump needs to be saved locally in a "shared volume" 
3. Once Saved, the "shared volume" needs to be mounted to Workspace 2. 
4. Workspace 2 can now take the dataset in the "shared volume" and perform required operations (Preprocessing, Augmentation, Training, etc)

I understand that the same can be achieved via Workflows, but having this kind of an option for Workspaces would increase flexibility and would potentially reduce the development time required for creating workflows and programs compatible with the same. 

**Describe the solution you'd like**
I do not have a possible solution for this so far, but one option might be to mount a common Storage to both Node Pools, Eg. AWS S3 Storage or Azure Blob Storage.
Ideally, this should work on all major platforms:
- Azure 
- AWS
- GCP

**Describe alternatives you've considered**
An alternative right now is to dump the CVAT annotations (Workspace 1) to download them locally and then followed by uploading them to the notebook (Workspace 2) and continue modification. However, this is completely manual and OnePanel does not add any value to this method.

**Comment by rushtehrani** [comment]
We are looking at using a combination of FileSyncer and having the annotations dump into a shared volume as a possible solution. 

Another (longer term) solution is using a distributed file system like Ceph (via Rook.io) to support this. 

Will update this issue when we have the first solution working.

**Comment by rushtehrani** [comment]
I am attaching very rough mockups for what is coming up next to address this issue - this will work for GCS, Azure blob storage and S3 and any S3 compatible object storage. Any feedback would be great!

**Syncing files between any Workspace and object storage**
![image](https://user-images.githubusercontent.com/1211823/105944114-88c41c00-6017-11eb-8ce4-1453ce59e247.png)

**Syncing files directly from Workflows to any Workspace**
![image](https://user-images.githubusercontent.com/1211823/105944265-d476c580-6017-11eb-903f-31af04cb5b71.png)

**Comment by rushtehrani** [comment]
First version of this has been implemented - here is a video showing how you can now easily sync models from a training Workflow to CVAT.

https://user-images.githubusercontent.com/1211823/107418155-2cf39b80-6acb-11eb-8d72-39b07f76fe8a.mp4

You could also train a model in JupyterLab and then sync the model to your object storage and then sync it back down to CVAT, all with a few clicks.

With the upcoming changes in #874, you can also sync annotation dumps to any other Workspace.
