### ISSUE TITLE
No files showing for a completed node in running workflow

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#84]
![image](https://user-images.githubusercontent.com/1211823/76126151-3b7c2d80-5fb3-11ea-9cf3-387eaad037cb.png)

**Comment by rushtehrani** [comment]
This is also most likely related:

https://www.loom.com/share/b8b903cd202b4e9d84b5c9f15323b57b

**Comment by Vafilor** [comment]
Fix is in https://github.com/onepanelio/core-ui/pull/26

Needs external testing to confirm.
