### ISSUE TITLE
Add CLI command for getting istio-ingressgateway external IP

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#85]
Need to display the istio gateway external IP/host before displaying the URL to user. This is only if the provider is cloud:

Message would be:
Please point your Wildcard FQDN (i.e. *.example.com or *.sub.example.com) in your DNS provider to <IP-or-HOST> as outlined in our docs.
Once the DNS propagates, your application will be available at <host>/<uiPath>

Sample `kubectl` command to get gateway external IP:
```
kubectl get service istio-ingressgateway -n istio-system
```
Relates to #89

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Should I try testing this on Azure?

**Comment by aleksandrmelnikov** [comment]
Also, is this supposed to display after the apply command finishes?

**Comment by rushtehrani** [comment]
> @rushtehrani Should I try developing this against Azure?

Azure has that pending issue with Istio still so the cluster won't run, they're supposed to have it fixed this week.

> Also, is this supposed to display after the apply command finishes?

Correct, we're basically extending/adjusting the current "Your application is running at ..." message.

**Comment by aleksandrmelnikov** [comment]
Full command:
```kubectl get service istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'```
