### ISSUE TITLE
External link for using CVAT

### ISSUE THREAD

**Issue by Armughan-Derq** [onepanelio/core#868]
Platform: GKE 

I have created a CVAT workspace and in order to annotate my data , I have to go through the main one panel UI, which requires token authentication.

The jobs uploaded on CVAT need to be labelled by third-party sources, so I cannot share one panel authentication token with them.
How can I get an external link to directly connect to CVAT . Instead of going through the one panel UI. the external link will allow the labellers to be authenticated using CVAT's authentication system.

(The question can also be expressed as what address will a NGINX server be hosted at if I use the NGINX template?)
P.s I am new with Kubernetes and so this question might be trivial.

**Comment by rushtehrani** [comment]
@Armughan-Derq I am working on a few scripts you can use to add users with Workspace specific access - I should have these tested and working by tomorrow.

**Comment by rushtehrani** [comment]
@Armughan-Derq here are the steps to add readonly users. 

Once you add them, you can just give them the URL to the CVAT Workspace. They will be prompted with the Onepanel login screen, once they log in, their users will be automatically created in CVAT. You can then assign them the correct role by clicking **Admin** > **Users** and their username in CVAT.

## Create readonly role

You only need to create these once.

1. Save the following as `role.yaml`:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onepanel-cluster-readonly
rules:
- apiGroups: ['']
  resources: [namespaces]
  verbs: [get, list]
- apiGroups: [onepanel.io]
  resources: [workspaces, workflows]
  verbs: [get, list]
```

2. Create the role:
```bash
kubectl apply -f role.yaml
```

3. Save the following as `role-binding.yaml`:
```bash
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onepanel-cluster-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepanel-cluster-readonly
subjects:
- kind: ServiceAccount
  name: admin
  namespace: onepanel
```

4. Create the role binding:
```bash
kubectl apply -f role-binding.yaml
```

## Adding a user

You can add multiple users as follows.

NOTE: In the commands below, replace `<username>` with the username you're adding

Create a service account:

```bash
kubectl create serviceaccount <username> -n onepanel
```

Bind the user to a role:

```bash
kubectl patch clusterrolebinding onepanel-cluster-readonly --type='json' -p='[{"op": "add", "path": "/subjects/-", "value": {"kind": "ServiceAccount", "name": "<username>","namespace": "onepanel" } }]'
```

Get the auth token for the user:

```bash
opctl auth token -u <username>
```

## Deleting a user

```bash
kubectl delete serviceaccount <username> -n onepanel
```

**Comment by rushtehrani** [comment]
Closing this issue - let us know if you still have any questions.

**Comment by suha-glal** [comment]
@rushtehrani Can I use the same script for Azure?
