### ISSUE TITLE
Use Kustomize package instead of calling exec.Command("kustomize", "build")

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#88]
An example of how `kubectl` does this:
https://github.com/kubernetes/cli-runtime/blob/master/pkg/kustomize/builder.go#L28

**Comment by aleksandrmelnikov** [comment]
@rushtehrani 
I don't think this will work without restructuring our kustomize files.

Explanation:
You're example is using cli-runtime, which uses Kustomize 2.0.3 as the base version.
- In fact, that's what cli-runtime master uses.
- https://github.com/kubernetes/cli-runtime uses https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/cli-runtime, which has https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/go.mod

We're using kustomize 3.x and higher (3.5.4)

I'm getting this error when I try to run it:
```2020/03/09 14:30:44 Error generating result rawResources failed to read Resources: Load from path common/onepanel/base failed: 'common/onepanel/base' must be a file (got d='/home/aleksandr/Code/onepanelio/cli/.manifests/cache/common/onepanel/base')```

**Comment by rushtehrani** [comment]
@aleksandrmelnikov can't you use these packages directly? 
```
"sigs.k8s.io/kustomize/pkg/commands/build"
"sigs.k8s.io/kustomize/pkg/fs"
```

**Comment by aleksandrmelnikov** [comment]
Testing

**Comment by aleksandrmelnikov** [comment]
@rushtehrani
As far as I can tell, trying those two imports uses kustomize/v2.0.3

```
sigs.k8s.io/kustomize v2.0.3+incompatible
```

I get this error:

```
2020/03/09 15:53:12 Error generating result rawResources failed to read Resources: Load from path common/onepanel/base failed: 'common/onepanel/base' must be a file (got d='/home/aleksandr/Code/onepanelio/cli/.manifests/cache/common/onepanel/base')
```
This is because it's Kustomize 2.x


I was trying to use Kustomize 3.5.x, but it does not seem like they expose the functions like they did for kustomize 2.x
```
	kv3 "sigs.k8s.io/kustomize/kustomize/v3/internal/commands"
```

![image-20200309155808576](https://user-images.githubusercontent.com/10407733/76264379-dcbaec00-621e-11ea-9d1a-9610aaf3fcdf.png)

I'm open for suggestions?

**Comment by aleksandrmelnikov** [comment]
```
	fSys := fs.MakeRealFS()
	stdOutTest := os.Stdout
	var o *build.Options
	o = build.NewOptions(localManifestsCopyPath, "")
	args := []string{localManifestsCopyPath}
	err = o.Validate(args)
	if err != nil {
		return "", err
	}
	factory := k8sdeps.NewFactory()
	err = o.RunBuild(stdOutTest, fSys, factory.ResmapF, factory.TransformerF)
	if err != nil {
		return "", err
	}```
