### ISSUE TITLE
Use Kubectl package instead of calling exec.Command("kubectl")

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#89]

**Comment by aleksandrmelnikov** [comment]
@rushtehrani Did you have a reference for this?
I'm having difficulty with replacing `kubectl apply -f <file>`

**Comment by aleksandrmelnikov** [comment]
Seeing this: https://github.com/kubernetes/enhancements/issues/555

**Comment by rushtehrani** [comment]
Also see: https://github.com/kubernetes/kubectl/blob/557a8af7da5b7012da2c1c40e215fca6eaa9fa64/pkg/cmd/apply/apply.go
