### ISSUE TITLE
Metrics endpoint should return 404 when there are none

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#95]
Right now the metrics endpoint returns a 500 if there are no metrics. It should return a 404.

**Comment by aleksandrmelnikov** [comment]
@Vafilor What about returning a "204 No Content" instead? The API url is valid, just no data.

**Comment by Vafilor** [comment]
@aleksandrmelnikov I was thinking about that. 

The issue is we might generate metrics at the end. Does it make more sense that you have `no metrics` or that they are `not found`, and later you do have metrics.

@rushtehrani Thoughts?

**Comment by aleksandrmelnikov** [comment]
If they can be at the end, I think it makes sense to use 204 in the middle.
- 404 means, to me, the url is invalid. Which is not the case if the metrics are in the middle and not yet generate.
- 204 means yes, valid, but no content (yet)
