### ISSUE TITLE
Missing or invalid authorization header after setup of MicroK8s on remote machine

### ISSUE THREAD

**Issue by jo-fra** [onepanelio/core#966]
**Describe the bug**
I was following the guide [MicroK8s on remote machines](https://docs.onepanel.ai/docs/deployment/configuration/remote-microk8s) until [Expose Onepanel using Nginx](https://docs.onepanel.ai/docs/deployment/configuration/remote-microk8s#expose-onepanel-using-nginx). After that I tried to open the onepanel app within my local browser using the IP address of the remote machine. I get the response `{"code":16,"message":"Missing or invalid \"authorization\" header.","details":[]}` in the browser.

**`opctl` version**
```bash
$ opctl version

CLI version: v1.0.2
Manifest version: v1.0.2
API version: v1.0.2
Web UI version: v1.0.2
```

**`opctl init` command**
`opctl init --provider microk8s --enable-metallb --artifact-repository-provider s3`

**Kubernetes information**
 - Cloud provider:  Microk8s
 - Kubernetes version: --channel=1.19/stable

**Machine information**
- OS: Ubuntu 20.04
- Browser: Chrome, MS Edge

**Comment by xxl007** [comment]
Configure your localhost through the /etc/hosts/ file [as described here](https://docs.onepanel.ai/docs/deployment/configuration/remote-microk8s#configure-local-dns). Then used the FQDN in the browser rather than the IP address.

**Comment by jo-fra** [comment]
Thanks, this resolved the issue! 
I was not aware that using the FQDN is mandatory.
